#ACTG Code

#Write a program that counts how many times each letter appears in a sequence and string of numbers

hello = """TCATCCGACGCCGAGGCTAATAGCAATTGACGTGGGTAGTACCTAGGGTAACATTACATG
GACCTCCTGTCGCACCTTTACTTCGCAGGGAGCTGCTTCGTACACGCGCTGTTCAGCCTA
AGTTTTCTGGCGCAGACTTACTCGGTTCGTCAGACCACCGTTATCGTGTTTATTAGTTTG
AGGAAATAGCTCCCTCGAAGTAGTGCAGTGCGGGGGCGAGCCAAACAAGGGGGCTCCGCG
CTACCTATTGTTCATTTCGGTGAGACAGTAACTAGTCGTTCGATAGCCGGCAAGCCTAAA
GCCTATTCGCAGTCCCATCAATAGGGGCATATGAATAGTTCCTGGGTTCCGTAAGTCCAG
ATTGCCCACAGGTACACTATTTAGTGCTGGGTGTGGTTGGTGCTCACTGCTTCTTGGGGC
ATGAAAGCGTATCCTTTTAACACTGTACGTGGAAGACTTTGAAACGGCCCTGCAGGCACT
ACTCGCGGTTGATAAAAGGCCGCGACGTAAAAAAACCATGTCAATTCGAACGAGGCACGA
TCACACCAATCATCTACTACGCCTGTATTAAACGGGAAAGGCACGGCCGAGGTAGAGTAC
TAGCTCCCAGTGGATACCGTTGAAGAGCGATTTAGTTACAAGATATTAACATTTGGGTAG
GTGGAGTCGTGTCAGTCTAACCCGCTGTCACGGTAGAAGTTGGATCGTAAAGTGAATGGA
ACACTCCCAGCCTTGCCTCAACCCGCATGATAGAAAAGATATCGAAGGGATAAAGCAGCT
AGGGGAGGATCAAGACTTTCTTGTGTCAAAACTCTTATCTTTGACCGCGATACTTCTGGA
TCGAGGATAGCTACTGGAGATATGTTACGGAGATTAGACGCCCGAAGATTTTTACAGTTT
CACTTTCCTTGTAGATTG"""

tally_c = 0.0
tally_g = 0.0
tally_a = 0.0
tally_t = 0.0
count = 0.0

for letter in hello:
    if letter == 'C':
        tally_c +=1
    if letter == 'G':
        tally_g +=1
    if letter == 'A':
        tally_a +=1
    if letter == 'T':
        tally_t +=1
    count +=1

def percentage(tally, count):
  return str((tally / count) * 100) + "%"


print("total: " + str(count)) 
print("C: " + str(tally_c) + " G: " + str(tally_g) + " A: " + str(tally_a) + " T: " + str(tally_t))
print("C: " + percentage(tally_c, count) + " G: " + percentage(tally_g, count) + " A: " + percentage(tally_a, count) + " T: "  + percentage(tally_t, count))
